// Build both files the entry ships.
//
// The entry directory gets exactly the files named in the manifest's launcher
// args, and there is no loader runtime next to it — so both halves bundle into
// one file each. `webui.js` is an IIFE for the browser; `launcher.js` is an ESM
// bundle for node, because the host spawns it directly and its five `src/server`
// modules would otherwise have to be five more installed files.
//
// Monaco's workers are inlined into webui.js as source strings and handed to it
// through `MonacoEnvironment.getWorkerUrl`, which turns each into a Blob URL at
// runtime. That keeps the "no loader runtime" promise while still giving Monaco
// real workers — the alternative, sibling `.js` files, would mean the manifest
// shipping five files and the installer copying five.
//
// Which workers, though, is a budget decision and the biggest one in this file:
//
//   - `editorWorkerService` — required. Word-based suggestions, diff computation
//     and link detection all live in it; 300 KB.
//   - `jsonWorkerService` — JSON's tokenizer *is* a worker in Monaco (there is no
//     basic-language definition for it), and JSON is everywhere in a JS repo. 427 KB.
//   - `typescriptWorkerService` — **left out on purpose.** It is 6.8 MB of
//     inlined TypeScript compiler, and a worker cannot see this workspace's
//     node_modules or tsconfig, so the type-checking it would perform is worse
//     than none: it reports errors against lib files that are not loaded and finds
//     nothing in the project. Shipping 6.8 MB to get a misleading answer is the
//     wrong trade. Add it when the workbench can hand the worker a real tsconfig.
//
// The result is a ~4.9 MB front-end. It is served from disk over loopback, so its
// size costs a moment's start-up and nothing per keystroke, and gzip on the wire
// takes it to roughly a megabyte.
//
// `webui.css` is not bundled into webui.js: the browser fetches it separately so
// the server can send it with a correct content-type and so the stylesheet can be
// iterated on without a rebuild. It is named in the manifest for the same reason
// the bundle is — that is what makes the installer copy it.
import esbuild from 'esbuild'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.dirname(fileURLToPath(import.meta.url))

// The keys are Monaco's own worker labels, and they are not uniform: the editor
// worker declares `label: 'editorWorkerService'` (editorWorkerService.ts), but each
// language service passes `label: this._defaults.languageId` — so JSON's worker is
// labelled `json`, not `jsonWorkerService`. Getting one of these wrong does not
// throw; `getWorkerUrl` falls back to the editor worker and that language simply
// stops highlighting, which is why it is worth stating rather than guessing.
const WORKERS = [
  ['editorWorkerService', 'monaco-editor/esm/vs/editor/editor.worker.js'],
  ['json', 'monaco-editor/esm/vs/language/json/json.worker.js'],
]

const banner = `/* meowui — generated by build.mjs. Do not edit; edit src/client/** instead. */`

// Monaco's UI CSS is not ours to ship: the workbench supplies its own theme, and
// a bundled stylesheet would land inside the IIFE where no stylesheet link can see
// it. So Monaco's CSS is stubbed out and its font is dropped — every glyph this
// workbench draws comes from the inline SVG icons in dom.mjs.
const STUB = {
  name: 'stub-monaco-assets',
  setup(build) {
    build.onLoad({ filter: /\.(css|ttf|woff2?)$/ }, () => ({ contents: '', loader: 'text' }))
  },
}

async function buildWorker(entry) {
  const result = await esbuild.build({
    entryPoints: [require_(entry)],
    bundle: true,
    minify: true,
    format: 'iife',
    write: false,
    target: 'es2022',
    // A worker has no module loader, so nothing may stay external.
    external: [],
    plugins: [STUB],
    logLevel: 'silent',
  })
  return result.outputFiles[0].text
}

// esbuild resolves bare specifiers from the entry's directory; inside build.mjs
// there is no `require`, so hand it an absolute path instead.
function require_(spec) {
  return path.join(ROOT, 'node_modules', spec)
}

async function main() {
  const workerSources = {}
  for (const [name, entry] of WORKERS) {
    workerSources[name] = await buildWorker(entry)
    process.stderr.write(`  worker ${name}: ${(workerSources[name].length / 1024).toFixed(0)} KB\n`)
  }

  // Handed to the client as a global, because the client is plain browser code
  // that cannot import from a build-time object.
  const workersDefine = {
    'process.env.MEOWUI_WORKERS': JSON.stringify(workerSources),
  }

  await esbuild.build({
    entryPoints: [path.join(ROOT, 'src/client/main.mjs')],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2022',
    outfile: path.join(ROOT, 'webui.js'),
    banner: { js: banner },
    minify: true,
    sourcemap: false,
    plugins: [STUB],
    define: {
      ...workersDefine,
      'process.env.NODE_ENV': '"production"',
    },
    logLevel: 'info',
  })

  const css = await fs.readFile(path.join(ROOT, 'src/client/workbench.css'), 'utf8')
  await fs.writeFile(path.join(ROOT, 'webui.css'), css)

  // The host side, same reasoning in the other direction: `node launcher.js` with
  // no loader beside it, so src/server/* has to end up inside one file too.
  await esbuild.build({
    entryPoints: [path.join(ROOT, 'src/launcher/main.mjs')],
    bundle: true,
    format: 'esm',
    platform: 'node',
    target: 'node20',
    outfile: path.join(ROOT, 'launcher.js'),
    banner: { js: banner },
    // Nothing external: the entry has no node_modules, so every import has to be
    // inside this file or it is a crash at startup. node: builtins are the one
    // exception and esbuild keeps those external by convention.
    external: ['node:*'],
    logLevel: 'info',
  })

  const js = await fs.stat(path.join(ROOT, 'webui.js'))
  const launcher = await fs.stat(path.join(ROOT, 'launcher.js'))
  process.stderr.write(`  webui.js   ${(js.size / 1024).toFixed(0)} KB\n`)
  process.stderr.write(`  launcher.js ${(launcher.size / 1024).toFixed(0)} KB\n`)
  process.stderr.write(`  webui.css  ${(Buffer.byteLength(css) / 1024).toFixed(0)} KB\n`)
}

main().catch((e) => {
  process.stderr.write('[meowui] build failed: ' + (e?.message ?? e) + '\n')
  if (e?.errors) for (const err of e.errors) process.stderr.write(`  ${err.text}\n`)
  process.exit(1)
})