/* meowui — generated by build.mjs. Do not edit; edit src/client/** instead. */

// src/launcher/main.mjs
import http2 from "node:http";
import path5 from "node:path";
import { spawn } from "node:child_process";

// src/server/rpc.mjs
import readline from "node:readline";
var HOST_PROTOCOL = "2025-meowcode-launcher-1";
var VERSION = "0.1.0";
var CALL_TIMEOUT_MS = 6e5;
var nextId = 1;
var pending = /* @__PURE__ */ new Map();
var eventListeners = /* @__PURE__ */ new Set();
var handshakeHandler = () => {
};
function send(message) {
  process.stdout.write(JSON.stringify(message) + "\n");
}
var reader;
function ensureReader() {
  if (reader) return;
  reader = readline.createInterface({ input: process.stdin });
  reader.on("line", onLine);
  reader.on("close", () => {
    for (const [, p] of pending) p.reject(new Error("the MeowCode host closed the bridge"));
    pending.clear();
  });
}
function onLine(line) {
  const text = line.trim();
  if (!text) return;
  let message;
  try {
    message = JSON.parse(text);
  } catch {
    return;
  }
  if (typeof message.id === "number" && pending.has(message.id)) {
    const p = pending.get(message.id);
    pending.delete(message.id);
    clearTimeout(p.timer);
    if (message.error) p.reject(new Error(message.error.message || "host error"));
    else p.resolve(message.result);
    return;
  }
  if (message.method === "initialize") {
    try {
      handshakeHandler(message.params);
    } catch {
    }
    send({
      jsonrpc: "2.0",
      id: message.id,
      result: { protocolVersion: HOST_PROTOCOL, name: "meowui", version: VERSION }
    });
    return;
  }
  if (message.method === "agent/event") {
    for (const fn of [...eventListeners]) {
      try {
        fn(message.params);
      } catch {
      }
    }
  }
}
function call(method, params = {}) {
  ensureReader();
  const id = nextId++;
  return new Promise((resolve, reject) => {
    const timer = setTimeout(() => {
      pending.delete(id);
      reject(new Error(`${method} timed out after ${CALL_TIMEOUT_MS}ms`));
    }, CALL_TIMEOUT_MS);
    pending.set(id, { resolve, reject, timer });
    send({ jsonrpc: "2.0", id, method, params });
  });
}
function onAgentEvent(fn) {
  ensureReader();
  eventListeners.add(fn);
  return () => eventListeners.delete(fn);
}
function createRpcClient({ onEvent, onHandshake } = {}) {
  handshakeHandler = onHandshake || (() => {
  });
  if (onEvent) onAgentEvent(onEvent);
  return { call, onAgentEvent };
}

// src/server/http.mjs
import http from "node:http";
import fsp from "node:fs/promises";
import path3 from "node:path";

// src/server/token.mjs
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
var FILE = ".meowui-token";
var BYTES = 32;
function loadToken(entryDir2) {
  const file = path.join(entryDir2, FILE);
  try {
    const existing = fs.readFileSync(file, "utf8").trim();
    if (existing.length >= 32) return { value: existing, created: false };
  } catch {
  }
  const value = crypto.randomBytes(BYTES).toString("base64url");
  return { value, created: true };
}
function saveToken(entryDir2, value) {
  const file = path.join(entryDir2, FILE);
  try {
    fs.writeFileSync(file + ".tmp", value, { mode: 384 });
    fs.renameSync(file + ".tmp", file);
    fs.chmodSync(file, 384);
  } catch (e) {
    process.stderr.write("[meowui] could not store the access token: " + (e instanceof Error ? e.message : e) + "\n");
  }
}
function tokenMatches(expected, given) {
  if (typeof given !== "string" || given.length !== expected.length) return false;
  return crypto.timingSafeEqual(Buffer.from(given), Buffer.from(expected));
}

// src/server/fsapi.mjs
import fs2 from "node:fs/promises";
import fsSync from "node:fs";
import path2 from "node:path";
var MAX_TEXT_BYTES = 2 * 1024 * 1024;
var SNIFF_BYTES = 4096;
var FsError = class extends Error {
  constructor(status, message) {
    super(message);
    this.status = status;
  }
};
var IGNORED = /* @__PURE__ */ new Set(["node_modules", ".git", "dist", ".cache", ".next", "build", ".venv", "__pycache__", "target", ".turbo"]);
function resolveInRoot(root, rel) {
  const raw = typeof rel === "string" ? rel : "";
  const target = path2.resolve(root, raw);
  const within = path2.relative(root, target);
  if (within.startsWith("..") || path2.isAbsolute(within)) {
    throw new FsError(403, "path outside the workspace");
  }
  return target;
}
async function realInRoot(root, target) {
  let real;
  try {
    real = await fs2.realpath(target);
  } catch (e) {
    if (e?.code === "ENOENT") return null;
    throw new FsError(400, e instanceof Error ? e.message : String(e));
  }
  const within = path2.relative(root, real);
  if (within.startsWith("..") || path2.isAbsolute(within)) {
    throw new FsError(403, "path outside the workspace");
  }
  return real;
}
function relTo(root, abs) {
  const rel = path2.relative(root, abs);
  return rel === "" ? "." : rel;
}
async function listDir(root, rel) {
  const target = resolveInRoot(root, rel);
  const real = await realInRoot(root, target);
  if (real === null) throw new FsError(404, "no such directory");
  const stat = await fs2.stat(real);
  if (!stat.isDirectory()) throw new FsError(400, "not a directory");
  if (await isSymlink(target)) throw new FsError(403, "refusing to follow a symlinked directory");
  const entries = await fs2.readdir(real, { withFileTypes: true });
  const out = [];
  for (const entry of entries) {
    const abs = path2.join(real, entry.name);
    const isDir = entry.isDirectory();
    const ignored = isDir && IGNORED.has(entry.name);
    out.push({
      name: entry.name,
      path: relTo(root, abs),
      dir: isDir,
      symlink: entry.isSymbolicLink(),
      ignored
    });
  }
  out.sort((a, b) => a.dir === b.dir ? a.name.localeCompare(b.name, void 0, { numeric: true, sensitivity: "base" }) : a.dir ? -1 : 1);
  return { path: relTo(root, real), entries: out };
}
async function readFile(root, rel) {
  const target = resolveInRoot(root, rel);
  const real = await realInRoot(root, target);
  if (real === null) throw new FsError(404, "no such file");
  if (await isSymlink(target)) throw new FsError(403, "refusing to follow a symlink");
  const stat = await fs2.stat(real);
  if (!stat.isFile()) throw new FsError(400, "not a file");
  if (stat.size > MAX_TEXT_BYTES) {
    throw new FsError(413, `file is ${(stat.size / 1048576).toFixed(1)} MB; the editor opens files under 2 MB`);
  }
  const head = Buffer.alloc(Math.min(SNIFF_BYTES, stat.size));
  const handle = await fs2.open(real, "r");
  try {
    await handle.read(head, 0, head.length, 0);
  } finally {
    await handle.close();
  }
  if (head.includes(0)) throw new FsError(415, "this looks like a binary file");
  return {
    path: relTo(root, real),
    content: await fs2.readFile(real, "utf8"),
    size: stat.size,
    mtimeMs: stat.mtimeMs
  };
}
async function createFile(root, rel) {
  const target = resolveInRoot(root, rel);
  const within = path2.relative(root, target);
  if (within.startsWith("..") || path2.isAbsolute(within)) throw new FsError(403, "path outside the workspace");
  const parent = path2.dirname(target);
  await fs2.mkdir(parent, { recursive: true });
  const handle = await fs2.open(target, "wx");
  await handle.close();
  return { path: relTo(root, target) };
}
function gitBranch(root) {
  const head = path2.join(root, ".git", "HEAD");
  try {
    const text = fsSync.readFileSync(head, "utf8").trim();
    const ref = /^ref:\s*refs\/heads\/(.+)$/.exec(text);
    if (ref) return ref[1];
    if (/^[0-9a-f]{40}$/.test(text)) return text.slice(0, 7);
    return "";
  } catch {
    return "";
  }
}
async function isSymlink(target) {
  try {
    return (await fs2.lstat(target)).isSymbolicLink();
  } catch {
    return false;
  }
}

// src/server/http.mjs
var COOKIE = "meowui_token";
var REPLAY_LIMIT = 500;
var KEEPALIVE_MS = 25e3;
var MIME = {
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".woff2": "font/woff2"
};
function createHttpApi({ port, token: token2, cwd: cwd2, entryDir: entryDir2, rpc: rpc2, bundle, css }) {
  const bundlePath = path3.resolve(entryDir2, bundle);
  const cssPath = path3.resolve(entryDir2, css);
  const clients = /* @__PURE__ */ new Set();
  const history = [];
  let nextEventId = 1;
  function frame(event) {
    return `id: ${event.id}
event: ${event.channel || "message"}
data: ${JSON.stringify(event)}

`;
  }
  function broadcast(payload) {
    const event = { ...payload, id: nextEventId++ };
    history.push(event);
    if (history.length > REPLAY_LIMIT) history.shift();
    for (const res of clients) {
      try {
        res.write(frame(event));
      } catch {
        clients.delete(res);
      }
    }
    return event;
  }
  const json = (res, status, body) => {
    const text = JSON.stringify(body);
    res.writeHead(status, {
      "content-type": "application/json; charset=utf-8",
      "content-length": Buffer.byteLength(text),
      "cache-control": "no-store"
    });
    res.end(text);
  };
  const fail = (res, status, message) => json(res, status, { error: message });
  function authorized(url2, req) {
    if (tokenMatches(token2, url2.searchParams.get("t"))) return true;
    const auth = req.headers.authorization;
    if (typeof auth === "string" && auth.startsWith("Bearer ") && tokenMatches(token2, auth.slice(7))) return true;
    const cookie = req.headers.cookie;
    if (typeof cookie === "string") {
      for (const part of cookie.split(";")) {
        const eq = part.indexOf("=");
        if (eq > 0 && part.slice(0, eq).trim() === COOKIE && tokenMatches(token2, part.slice(eq + 1).trim())) return true;
      }
    }
    return false;
  }
  async function readBody(req, limit = 8 * 1024 * 1024) {
    const chunks = [];
    let size = 0;
    for await (const chunk of req) {
      size += chunk.length;
      if (size > limit) throw new FsError(413, "request body too large");
      chunks.push(chunk);
    }
    if (!chunks.length) return {};
    try {
      return JSON.parse(Buffer.concat(chunks).toString("utf8"));
    } catch {
      throw new FsError(400, "body must be JSON");
    }
  }
  async function serveStatic(res, file) {
    try {
      const body = await fsp.readFile(file);
      res.writeHead(200, {
        "content-type": MIME[path3.extname(file)] || "application/octet-stream",
        "content-length": body.length,
        // The bundle changes on every rebuild; a cached copy is a mystifying bug.
        "cache-control": "no-store"
      });
      res.end(body);
    } catch {
      fail(res, 404, `${path3.basename(file)} is missing \u2014 run \`npm run build\` in the plugin directory`);
    }
  }
  const PAGE = `<!doctype html>
<html lang="en" data-theme="dark">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>meowui</title>
<link rel="stylesheet" href="/${css}?t=${encodeURIComponent(token2)}">
</head>
<body>
<div id="root"></div>
<script>
// The only part of the front-end that does not need the bundle to exist, which is
// precisely why the boot watchdog is here rather than in webui.js.
//
// A 401 on the bundle is silent: a script element that errors out never runs, so
// the console says nothing and #root stays empty. Three ways that can happen, and
// each needs its own trigger:
//
//   - never fetched      -> the script element's onerror attribute, below
//   - fetched, throws
//     while evaluating   -> window's error event, which an uncaught exception in a
//                            classic script always reaches
//   - fetched, hangs     -> only a timer can see this one
//
// The timer is generous because a cold 4.7 MB parse on a busy machine is slow,
// not broken.
//
// Note what the bundle's own __meowuiBooted flag cannot do: an ES module's imports
// are all evaluated before its first statement, so main.mjs cannot set that flag
// until Monaco has finished loading. A Monaco that throws is therefore invisible to
// the flag and is caught by the error listener instead.
(function () {
  var root = document.getElementById('root')
  window.MEOWUI_TOKEN = new URLSearchParams(location.search).get('t') || ''
  var timer = setTimeout(function () { fail('webui.js never finished loading') }, 8000)
  function fail(why) {
    if (window.__meowuiBooted) return
    clearTimeout(timer)
    var box = document.createElement('div')
    box.className = 'boot-error'
    var head = document.createElement('div')
    head.className = 'head'
    head.textContent = 'the workbench did not start'
    var reason = document.createElement('div')
    reason.className = 'why'
    reason.textContent = why
    var hint = document.createElement('div')
    hint.className = 'hint'
    hint.textContent = 'Open the exact URL MeowCode printed, token and all \u2014 a bare 127.0.0.1 address is not enough.'
    box.append(head, reason, hint)
    root.replaceChildren(box)
  }
  window.__meowuiFail = fail
  window.addEventListener('error', function (e) {
    fail('webui.js failed while loading: ' + (e.message || 'an unknown error'))
  })
})();
</script>
<script src="/${bundle}?t=${encodeURIComponent(token2)}" onerror="window.__meowuiFail &amp;&amp; window.__meowuiFail('webui.js could not be loaded \u2014 the server answered with an error')"></script>
</body>
</html>`;
  const NO_TOKEN_PAGE = `<!doctype html><meta charset="utf-8"><title>meowui</title>
<body style="font:14px system-ui;padding:2rem">
<p>This workbench needs the access token from the URL MeowCode printed on its stderr.</p>
<p>Open the full URL, not just <code>127.0.0.1:${port}</code>.</p>`;
  async function handle(req, res) {
    const url2 = new URL(req.url, `http://127.0.0.1:${port}`);
    if (!authorized(url2, req)) {
      if (url2.pathname === "/" || url2.pathname === "/index.html") {
        res.writeHead(401, { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" });
        res.end(NO_TOKEN_PAGE);
        return;
      }
      fail(res, 401, "bad or missing token");
      return;
    }
    const p = url2.pathname;
    if (req.method === "GET" && (p === "/" || p === "/index.html")) {
      res.writeHead(200, { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" });
      res.end(PAGE);
      return;
    }
    if (req.method === "GET" && p === "/" + bundle) return serveStatic(res, bundlePath);
    if (req.method === "GET" && p === "/" + css) return serveStatic(res, cssPath);
    if (req.method === "GET" && p === "/api/cwd") return json(res, 200, { cwd: cwd2 });
    if (req.method === "GET" && p === "/api/git") return json(res, 200, { branch: gitBranch(cwd2) });
    if (req.method === "GET" && p === "/api/fs/tree") {
      return json(res, 200, await listDir(cwd2, url2.searchParams.get("path") || "."));
    }
    if (req.method === "GET" && p === "/api/fs/file") {
      return json(res, 200, await readFile(cwd2, url2.searchParams.get("path") || ""));
    }
    if (req.method === "POST" && p === "/api/fs/new") {
      const body = await readBody(req);
      return json(res, 200, await createFile(cwd2, String(body.path ?? "")));
    }
    if (req.method === "GET" && p === "/api/config") return json(res, 200, await rpc2.call("config/get"));
    if (req.method === "GET" && p === "/api/state") return json(res, 200, await rpc2.call("session/state"));
    if (req.method === "GET" && p === "/api/tools") return json(res, 200, await rpc2.call("tools/list"));
    if (req.method === "POST" && p === "/api/turn") {
      const body = await readBody(req);
      return json(res, 200, await rpc2.call("agent/turn", { prompt: String(body.prompt ?? "") }));
    }
    if (req.method === "POST" && p === "/api/abort") return json(res, 200, await rpc2.call("agent/abort"));
    if (req.method === "POST" && p === "/api/reset") {
      const out = await rpc2.call("session/reset");
      broadcast({ channel: "reset" });
      return json(res, 200, out);
    }
    if (req.method === "POST" && p === "/api/tool") {
      const body = await readBody(req);
      return json(res, 200, await rpc2.call("tools/call", { name: String(body.name ?? ""), input: body.input ?? {} }));
    }
    if (req.method === "GET" && p === "/api/events") {
      res.writeHead(200, {
        "content-type": "text/event-stream; charset=utf-8",
        "cache-control": "no-store",
        connection: "keep-alive"
      });
      res.write("retry: 1000\n\n");
      const since = Number(req.headers["last-event-id"]);
      if (Number.isFinite(since) && since > 0) {
        for (const event of history) if (event.id > since) res.write(frame(event));
      }
      clients.add(res);
      const keepAlive = setInterval(() => {
        try {
          res.write(": keep-alive\n\n");
        } catch {
          clients.delete(res);
        }
      }, KEEPALIVE_MS);
      req.on("close", () => {
        clearInterval(keepAlive);
        clients.delete(res);
      });
      return;
    }
    fail(res, 404, `no route for ${req.method} ${p}`);
  }
  const server = http.createServer((req, res) => {
    handle(req, res).catch((e) => {
      const status = typeof e?.status === "number" ? e.status : 500;
      if (!res.headersSent) fail(res, status, e instanceof Error ? e.message : String(e));
      else try {
        res.end();
      } catch {
      }
    });
  });
  const ready = new Promise((resolve, reject) => {
    server.once("error", reject);
    server.listen(port, "127.0.0.1", () => {
      server.removeListener("error", reject);
      server.on("error", (e) => process.stderr.write("[meowui] server error: " + e.message + "\n"));
      resolve();
    });
  });
  ready.catch(() => {
  });
  return {
    ready,
    broadcast,
    url(t) {
      return `http://127.0.0.1:${port}/?t=${encodeURIComponent(t)}`;
    },
    close() {
      for (const res of clients) {
        try {
          res.end();
        } catch {
        }
      }
      clients.clear();
      try {
        server.close();
      } catch {
      }
    }
  };
}

// src/server/watcher.mjs
import fs3 from "node:fs";
import path4 from "node:path";
var DEBOUNCE_MS = 150;
function shouldSkip(abs) {
  const parts = abs.split("/");
  return parts.includes(".git") || parts.includes("node_modules");
}
function watchWorkspace(root, onChanged) {
  let watcher2;
  try {
    watcher2 = fs3.watch(root, { recursive: true, persistent: false }, (_event, filename) => {
      if (!filename) return;
      const abs = path4.resolve(root, filename.toString());
      if (shouldSkip(abs)) return;
      pending2.add(abs);
      schedule();
    });
  } catch (e) {
    process.stderr.write("[meowui] file watching unavailable (" + (e instanceof Error ? e.message : e) + ")\n");
    return { close() {
    } };
  }
  const pending2 = /* @__PURE__ */ new Set();
  let timer = null;
  function schedule() {
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => {
      timer = null;
      const changed = [...pending2].map((abs) => path4.relative(root, abs));
      pending2.clear();
      if (changed.length) onChanged(changed);
    }, DEBOUNCE_MS);
  }
  return {
    close() {
      if (timer) clearTimeout(timer);
      try {
        watcher2.close();
      } catch {
      }
    }
  };
}

// src/launcher/main.mjs
var HOST_PROTOCOL2 = "2025-meowcode-launcher-1";
var DEFAULT_PORT = 4711;
function log(...args) {
  process.stderr.write("[meowui] " + args.join(" ") + "\n");
}
var rpc = createRpcClient({
  onEvent(params) {
    api.broadcast({ channel: "agent", ...params });
  },
  onHandshake(info) {
    log("host handshake:", JSON.stringify(info ?? {}));
    if (info?.protocolVersion && info.protocolVersion !== HOST_PROTOCOL2) {
      log(`warning: host speaks ${info.protocolVersion}, this front-end was written for ${HOST_PROTOCOL2}`);
    }
  }
});
var cwd = process.cwd();
log("workspace:", cwd);
var entryDir = path5.dirname(path5.resolve(process.argv[1]));
var token = loadToken(entryDir);
if (token.created) saveToken(entryDir, token.value);
var api;
try {
  api = createHttpApi({
    port: Number(process.env.MEOWUI_PORT || DEFAULT_PORT),
    token: token.value,
    cwd,
    entryDir,
    rpc,
    // Named relative to this bundle, not to the workspace. Both strings are also
    // listed in the manifest's `launcher.args`, which is the only thing that makes
    // the entry installer copy them — the installer ships files named in the
    // manifest and nothing else, so a file the front-end needs must appear there
    // even though the launcher never passes one of them as an argument.
    bundle: process.env.MEOWUI_BUNDLE || "webui.js",
    css: "webui.css"
  });
  await api.ready;
} catch (e) {
  log(e instanceof Error ? e.message : String(e));
  log("set MEOWUI_PORT to pick a different port");
  process.exit(1);
}
var url = api.url(token.value);
log("workbench:", url);
var watcher = watchWorkspace(cwd, (changed) => api.broadcast({ channel: "fs", changed }));
var BROWSERS = [
  ["xdg-open", []],
  ["gio", ["open"]],
  ["gnome-open", []],
  ["kde-open", []],
  ["wslview", []],
  ["open", []]
];
async function openInBrowser(target) {
  if (process.env.MEOWUI_OPEN === "0") return;
  const candidates = process.env.MEOWUI_BROWSER ? [[process.env.MEOWUI_BROWSER, []]] : BROWSERS;
  for (const [command, prefix] of candidates) {
    if (await tryOpen(command, [...prefix, target])) return;
  }
  log("no browser here \u2014 open the URL above by hand");
}
function tryOpen(command, args) {
  return new Promise((resolve) => {
    let child;
    try {
      child = spawn(command, args, { stdio: "ignore", detached: true });
    } catch {
      resolve(false);
      return;
    }
    const grace = setTimeout(() => {
      child.unref();
      resolve(true);
    }, 400);
    child.on("error", () => {
      clearTimeout(grace);
      resolve(false);
    });
  });
}
process.stdin.on("end", () => {
  log("host closed the bridge");
  shutdown(0);
});
process.on("SIGINT", () => shutdown(0));
process.on("SIGTERM", () => shutdown(0));
openInBrowser(url).catch((e) => log(`could not open a browser: ${e?.message ?? e}`));
var closing = false;
function shutdown(code) {
  if (closing) return;
  closing = true;
  try {
    watcher.close();
  } catch {
  }
  try {
    api.close();
  } catch {
  }
  process.exit(code);
}
